import { api } from './api.js';
import { escapeHtml, prettyJson, toast, viewHeader } from './components.js';

export async function renderDiagnostics(root) {
  root.innerHTML=`${viewHeader('Diagnostics','Service health, container resolution, ROS graph, heartbeats, ports, packet state, and actionable failure analysis.',`<button class="button secondary" id="diag-refresh">Refresh</button><button class="button primary" id="diag-packet">Run Packet Doctor</button>`)}<div class="card"><div class="empty-state"><div><strong>Running diagnostics…</strong></div></div></div>`;
  const [system,packet]=await Promise.all([api.diagnostics(),api.packetDoctor()]);
  const serviceRows=Object.entries(system.services||{}).map(([name,service])=>`<tr><td>${escapeHtml(name)}</td><td>${escapeHtml(service.container||'not resolved')}</td><td><span class="status-chip ${service.running?'ready':'error'}">${service.running?'RUNNING':'STOPPED'}</span></td><td>${escapeHtml(service.health||service.status||'unknown')}</td><td>${escapeHtml(service.error||'')}</td></tr>`).join('');
  const findings=[...(system.findings||[]),...(packet.findings||[])];
  root.innerHTML=`${viewHeader('Diagnostics','Service health, container resolution, ROS graph, heartbeats, ports, packet state, and actionable failure analysis.',`<button class="button secondary" id="diag-refresh">Refresh</button><button class="button primary" id="diag-packet">Run Packet Doctor</button>`)}
  <div class="grid four"><article class="card metric-card"><div class="metric-label">Docker daemon</div><div class="metric-value" style="font-size:20px">${system.docker?.reachable?'REACHABLE':'UNAVAILABLE'}</div><div class="metric-detail">${escapeHtml(system.docker?.server_version||system.docker?.error||'')}</div></article><article class="card metric-card"><div class="metric-label">GPU probe</div><div class="metric-value" style="font-size:20px">${system.gpu?.available?'AVAILABLE':'UNAVAILABLE'}</div><div class="metric-detail">${escapeHtml(system.gpu?.gpus?.[0]?.name||system.gpu?.error||'')}</div></article><article class="card metric-card"><div class="metric-label">Packet heartbeat</div><div class="metric-value" style="font-size:20px">${packet.heartbeat_freshness?.fresh?'FRESH':'STALE / MISSING'}</div><div class="metric-detail">${packet.heartbeat_freshness?.age_s==null?'No file':`${packet.heartbeat_freshness.age_s} s old`}</div></article><article class="card metric-card"><div class="metric-label">Isaac sync</div><div class="metric-value" style="font-size:20px">${escapeHtml(system.isaac_sync?.state||'UNKNOWN')}</div><div class="metric-detail">Heartbeat and scenario-revision acknowledgement</div></article></div>
  <section class="card" style="margin-top:16px"><div class="card-header"><div><h2>Compose service resolution</h2><p class="card-description">Services resolve through Compose and Docker labels; ephemeral prefixed container names are supported.</p></div></div><div class="table-wrap"><table><thead><tr><th>Service</th><th>Resolved container</th><th>Runtime</th><th>Health</th><th>Error</th></tr></thead><tbody>${serviceRows}</tbody></table></div></section>
  <div class="grid two" style="margin-top:16px"><section class="card"><h2>Findings</h2><div class="stack">${findings.length?findings.map(item=>`<div class="callout ${item.severity==='ERROR'?'error':'warning'}"><div class="callout-title">${escapeHtml(item.code)}</div><div>${escapeHtml(item.message||'')}</div>${item.action?`<div class="small-text" style="margin-top:5px"><strong>Action:</strong> ${escapeHtml(item.action)}</div>`:''}</div>`).join(''):`<div class="callout success"><div class="callout-title">No blocking findings</div><div>All observable diagnostics are coherent.</div></div>`}</div></section><section class="card"><h2>ROS graph summary</h2><div class="table-wrap"><table><tbody><tr><th>Container</th><td>${escapeHtml(packet.container||'not resolved')}</td></tr><tr><th>Nodes</th><td>${packet.ros?.node_list?.length||0}</td></tr><tr><th>Topics</th><td>${packet.ros?.topic_list?.length||0}</td></tr><tr><th>Runtime processes</th><td>${packet.ros?.runtime_processes?.length||0}</td></tr><tr><th>Latest gate</th><td>${escapeHtml(packet.latest_metric?.gate_reason||packet.latest_gate?.reason||'unavailable')}</td></tr></tbody></table></div></section></div>
  <details class="card" style="margin-top:16px"><summary><strong>Packet Doctor full report</strong></summary><div style="margin-top:14px">${prettyJson(packet)}</div></details><details class="card" style="margin-top:16px"><summary><strong>System diagnostics full report</strong></summary><div style="margin-top:14px">${prettyJson(system)}</div></details>`;
  root.querySelector('#diag-refresh').addEventListener('click',()=>renderDiagnostics(root));root.querySelector('#diag-packet').addEventListener('click',()=>renderDiagnostics(root));
}
