import { api } from './api.js';
import { escapeHtml, prettyJson, toast, viewHeader } from './components.js';

export async function renderFaultRecovery(root) {
  const [configResponse,eventsResponse]=await Promise.all([api.config(),api.events(100)]); let config=structuredClone(configResponse.config || {}); config.failures ||= { recovery_policy: 'none', failure_detection_s: 1, recovery_timeout_s: 20, retry_limit: 3, schedule: [] }; config.failures.schedule = Array.isArray(config.failures.schedule) ? config.failures.schedule : []; config.swarm ||= {}; config.swarm.drones = Array.isArray(config.swarm.drones) ? config.swarm.drones : []; eventsResponse.events = Array.isArray(eventsResponse.events) ? eventsResponse.events : []; const schedule=config.failures.schedule;
  const render=()=>{root.innerHTML=`${viewHeader('Fault & Recovery','Schedule explicit failures, inject runtime faults, select recovery policy, and verify that restored routes satisfy the same communication-feasibility gate.',`<button class="button secondary" id="failure-add">Add Scheduled Failure</button><button class="button primary" id="failure-save">Apply Failure Policy</button>`)}
    <div class="grid two"><section class="card"><div class="card-header"><div><h2>Immediate fault injection</h2><p class="card-description">Choose a UAV and inject or heal a complete endpoint failure.</p></div></div><div class="row"><select id="failure-uav">${config.swarm.drones.map(d=>`<option value="${d.index}">${escapeHtml(d.id)} — ${escapeHtml(d.role)}</option>`).join('')}</select><button class="button danger" id="failure-inject">Inject Failure</button><button class="button secondary" id="failure-heal">Heal UAV</button><button class="button warning" id="failure-recompute">Recompute Topology</button></div><div class="callout warning" style="margin-top:16px"><div class="callout-title">Recovery acceptance</div><div>Promotion or rerouting is not successful until every new active hop passes endpoint, range, hard-outage, SNR/SINR, capacity, and freshness predicates and packet advancement resumes.</div></div></section>
    <section class="card"><h2>Recovery policy</h2><div class="form-grid"><label class="field"><span><strong>Policy</strong></span><select id="recovery-policy">${['none','topology_recomputation','standby_promotion','nearest_feasible_standby','energy_aware_standby','communication_aware_standby','plugin'].map(v=>`<option value="${v}" ${config.failures.recovery_policy===v?'selected':''}>${v}</option>`).join('')}</select></label><label class="field"><span><strong>Detection latency</strong> <span class="unit">s</span></span><input id="failure-detection" type="number" step="any" value="${config.failures.failure_detection_s}"></label><label class="field"><span><strong>Recovery timeout</strong> <span class="unit">s</span></span><input id="recovery-timeout" type="number" step="any" value="${config.failures.recovery_timeout_s}"></label><label class="field"><span><strong>Retry limit</strong></span><input id="recovery-retries" type="number" value="${config.failures.retry_limit}"></label></div></section></div>
    <section class="card" style="margin-top:16px"><div class="card-header"><div><h2>Failure schedule</h2><p class="card-description">Events are expressed in simulation time.</p></div></div><div class="table-wrap"><table><thead><tr><th>ID</th><th>Type</th><th>Target</th><th>Start (s)</th><th>Duration (s)</th><th>Severity</th><th></th></tr></thead><tbody>${schedule.length?schedule.map((item,index)=>`<tr data-schedule="${index}"><td><input data-key="id" value="${escapeHtml(item.id||`failure_${index+1}`)}"></td><td><select data-key="type">${['uav_complete','radio_failure','antenna_failure','antenna_misalignment','battery_depletion','controller_timeout','gps_degradation','link_service_failure','blockage','interference'].map(v=>`<option value="${v}" ${item.type===v?'selected':''}>${v}</option>`).join('')}</select></td><td><input data-key="target" value="${escapeHtml(item.target||'drone_3')}"></td><td><input data-key="start_time_s" type="number" step="any" value="${item.start_time_s||0}"></td><td><input data-key="duration_s" type="number" step="any" value="${item.duration_s||0}"></td><td><select data-key="severity">${['degraded','major','critical'].map(v=>`<option value="${v}" ${item.severity===v?'selected':''}>${v}</option>`).join('')}</select></td><td><button class="button danger small" data-schedule-delete="${index}">Delete</button></td></tr>`).join(''):`<tr><td colspan="7"><div class="empty-state"><div><strong>No scheduled failures</strong><div class="small-text">Runtime injection remains available above.</div></div></div></td></tr>`}</tbody></table></div></section>
    <section class="card" style="margin-top:16px"><h2>Recent resilience events</h2>${prettyJson(eventsResponse.events.slice(-30))}</section>`;
    function collect(){config.failures.recovery_policy=root.querySelector('#recovery-policy').value;config.failures.failure_detection_s=Number(root.querySelector('#failure-detection').value);config.failures.recovery_timeout_s=Number(root.querySelector('#recovery-timeout').value);config.failures.retry_limit=Number(root.querySelector('#recovery-retries').value);root.querySelectorAll('[data-schedule]').forEach(row=>{const item=schedule[Number(row.dataset.schedule)];for(const key of ['id','type','target','severity'])item[key]=row.querySelector(`[data-key="${key}"]`).value;for(const key of ['start_time_s','duration_s'])item[key]=Number(row.querySelector(`[data-key="${key}"]`).value)})}
    root.querySelector('#failure-add').addEventListener('click',()=>{schedule.push({id:`failure_${schedule.length+1}`,type:'uav_complete',target:'drone_3',start_time_s:60,duration_s:0,severity:'critical'});render()});root.querySelectorAll('[data-schedule-delete]').forEach(button=>button.addEventListener('click',()=>{schedule.splice(Number(button.dataset.scheduleDelete),1);render()}));
    for(const [id,command] of [['failure-inject','fail_uav'],['failure-heal','heal_uav'],['failure-recompute','recompute_topology']])root.querySelector(`#${id}`).addEventListener('click',async()=>{try{await api.command(command,{index:Number(root.querySelector('#failure-uav').value)});toast(`${command.replaceAll('_',' ')} was acknowledged.`,'success')}catch(error){toast(error.message,'error')}});
    root.querySelector('#failure-save').addEventListener('click',async event=>{event.currentTarget.disabled=true;try{collect();const result=await api.saveConfig(config,true);config=structuredClone(result.config);toast('Failure schedule and recovery policy were saved and synchronized.','success');render()}catch(error){toast(error.message,'error')}finally{event.currentTarget.disabled=false}})
  };render();
}
