import { api } from './api.js';import { preferences } from './storage.js';
import { escapeHtml, prettyJson, toast, viewHeader } from './components.js';

export async function renderSettings(root) {
  const [health,config]=await Promise.all([api.health(),api.config()]);
  root.innerHTML=`${viewHeader('Settings','Operator preferences and authoritative runtime endpoints. Scientific settings belong in Mission Designer, Antenna Lab, or World Lab.',`<button class="button primary" id="settings-save">Save Preferences</button>`)}
  <div class="grid two"><section class="card"><h2>Operator preferences</h2><div class="stack"><label class="field"><span><strong>Refresh interval</strong> <span class="unit">ms</span></span><input id="settings-refresh" type="number" min="500" max="60000" value="${preferences.get('netlab.refreshMs')||2000}"></label><label class="field"><span><strong>Default theme</strong></span><select id="settings-theme"><option value="light">Light</option><option value="dark" ${document.documentElement.dataset.theme==='dark'?'selected':''}>Dark</option></select></label><label class="checkbox-field"><input id="settings-confirm-destructive" type="checkbox" ${preferences.get('netlab.confirmDestructive')!=='false'?'checked':''}><span>Require confirmation for destructive actions</span></label></div></section><section class="card"><h2>Service identity</h2><div class="table-wrap"><table><tbody><tr><th>Mission Control</th><td>${escapeHtml(health.service)}</td></tr><tr><th>Version</th><td>${escapeHtml(health.version)}</td></tr><tr><th>API version</th><td>${escapeHtml(health.api_version)}</td></tr><tr><th>Sionna endpoint</th><td>${escapeHtml(config.config.runtime.sionna_url)}</td></tr><tr><th>Configuration hash</th><td><code>${escapeHtml(config.hash)}</code></td></tr></tbody></table></div></section></div>
  <section class="card" style="margin-top:16px"><h2>Configuration compatibility</h2><p class="muted">The v5 schema emits a controlled legacy payload for current ROS and Isaac adapters while the migration remains active. Compatibility adapters have explicit removal conditions in the architecture documentation.</p>${prettyJson(config.config.compatibility)}</section>`;
  root.querySelector('#settings-save').addEventListener('click',()=>{preferences.set('netlab.refreshMs',root.querySelector('#settings-refresh').value);preferences.set('netlab.confirmDestructive',String(root.querySelector('#settings-confirm-destructive').checked));document.documentElement.dataset.theme=root.querySelector('#settings-theme').value;preferences.set('netlab.theme',root.querySelector('#settings-theme').value);toast('Operator preferences saved.','success')});
}
