import { api } from './api.js';
import { escapeHtml, prettyJson, toast, viewHeader } from './components.js';

export async function renderEvidence(root) {
  const [evidence,events]=await Promise.all([api.evidence(),api.events(200)]);const index=evidence.index||{items:[]};
  root.innerHTML=`${viewHeader('Evidence','Inspect reproducibility artifacts, hashes, event records, run manifests, metrics, and logs. Evidence source and test scope remain explicit.',`<button class="button secondary" id="evidence-refresh">Rebuild Index</button><button class="button primary" id="evidence-download">Download Index</button>`)}
  <div class="grid four"><article class="card metric-card"><div class="metric-label">Indexed artifacts</div><div class="metric-value">${index.item_count||0}</div><div class="metric-detail">Files below runtime results root</div></article><article class="card metric-card"><div class="metric-label">Structured events</div><div class="metric-value">${events.events.length}</div><div class="metric-detail">Current bounded event view</div></article><article class="card metric-card"><div class="metric-label">Hashed artifacts</div><div class="metric-value">${(index.items||[]).filter(item=>item.sha256).length}</div><div class="metric-detail">SHA-256 recorded</div></article><article class="card metric-card"><div class="metric-label">Index generated</div><div class="metric-value" style="font-size:18px">${index.generated_at?new Date(index.generated_at*1000).toLocaleString():'—'}</div><div class="metric-detail">Evidence inventory timestamp</div></article></div>
  <section class="card" style="margin-top:16px"><div class="card-header"><div><h2>Artifact inventory</h2><p class="card-description">Large artifacts may omit content hashes according to the configured safety limit.</p></div></div><div class="table-wrap"><table><thead><tr><th>Path</th><th>Size</th><th>SHA-256</th></tr></thead><tbody>${(index.items||[]).length?(index.items||[]).map(item=>`<tr><td>${escapeHtml(item.path)}</td><td>${Number(item.size_bytes||0).toLocaleString()} bytes</td><td><code>${escapeHtml(item.sha256||'not calculated')}</code></td></tr>`).join(''):`<tr><td colspan="3"><div class="empty-state"><div><strong>No evidence files are present.</strong><div class="small-text">Start an experiment to create a run manifest and metrics.</div></div></div></td></tr>`}</tbody></table></div></section>
  <details class="card" style="margin-top:16px"><summary><strong>Recent structured events</strong></summary><div style="margin-top:14px">${prettyJson(events.events)}</div></details>`;
  root.querySelector('#evidence-refresh').addEventListener('click',()=>renderEvidence(root));root.querySelector('#evidence-download').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(index,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='netlab_evidence_index.json';a.click();URL.revokeObjectURL(url);toast('Evidence index downloaded.','success')});
}
