import { api } from './api.js';
import { escapeHtml, formatNumber, lineChart, metricCard, prettyJson, sourceBadge, toast, viewHeader } from './components.js';
import { state } from './state.js';

export async function renderLiveTelemetry(root) {
  let stopped=false; let snapshot=null;
  const render=async()=>{try{snapshot=await api.telemetry();state.set('telemetry',snapshot);draw()}catch(error){root.innerHTML=`${viewHeader('Live Telemetry','Measured runtime metrics with explicit source and freshness labels.')}<div class="callout error"><div class="callout-title">Telemetry request failed</div><div>${escapeHtml(error.message)}</div></div>`}};
  const draw=()=>{if(stopped||state.currentView!=='telemetry')return;const source=snapshot.source||{source:'OFFLINE'};const analytics=snapshot.analytics||{};const rows=snapshot.rows||[];const events=snapshot.events||[];const latest=rows.at(-1)||{};
    root.innerHTML=`${viewHeader('Live Telemetry','Live, replay, preview, stale, and offline data are never conflated. Charts update from measured metric rows only.',`<button class="button secondary" id="telemetry-refresh">Refresh Now</button><button class="button secondary" id="telemetry-export">Export Snapshot</button>`)}
    <div class="row" style="margin-bottom:16px">${sourceBadge(source.source)}<span class="muted">${escapeHtml(source.reason||'')}</span><span class="status-chip ${source.source==='LIVE'?'ready':'warning'}">${source.age_s==null?'AGE UNAVAILABLE':`${formatNumber(source.age_s,2)} s old`}</span></div>
    <div class="grid four">${metricCard('Packet delivery ratio',`${formatNumber((analytics.packet_delivery_ratio||0)*100,1)}%`,'',`${analytics.delivered_packets||0} delivered`)}${metricCard('Link feasibility ratio',`${formatNumber((analytics.link_feasibility_ratio||0)*100,1)}%`,'',`${analytics.feasible_samples||0} feasible / ${analytics.blocked_samples||0} blocked`)}${metricCard('Metric samples',analytics.samples||0,'','Bounded telemetry window')}${metricCard('Outage events',analytics.outage_events||0,'',`${analytics.recovery_events||0} recovery events`)}</div>
    <div class="grid three" style="margin-top:16px"><section class="card"><div class="card-header"><div><h2>SNR</h2><p class="card-description">Per-hop measured or calculated runtime values.</p></div></div><div class="chart">${lineChart(rows.map(row=>row.snr_db),{label:'SNR',unit:'dB'})}</div></section><section class="card"><div class="card-header"><div><h2>Capacity</h2><p class="card-description">Theoretical or model-derived capacity; not automatically application goodput.</p></div></div><div class="chart">${lineChart(rows.map(row=>row.capacity_mbps),{label:'Capacity',unit:'Mbps'})}</div></section><section class="card"><div class="card-header"><div><h2>Distance</h2><p class="card-description">Inter-node distance for evaluated hops.</p></div></div><div class="chart">${lineChart(rows.map(row=>row.distance_m),{label:'Distance',unit:'m'})}</div></section></div>
    <div class="grid two" style="margin-top:16px"><section class="card"><div class="card-header"><div><h2>Latest link decision</h2><p class="card-description">Current measured values and gate reason.</p></div></div>${rows.length?`<div class="table-wrap"><table><tbody><tr><th>Link</th><td>${escapeHtml(latest.src||'—')} → ${escapeHtml(latest.dst||'—')}</td></tr><tr><th>Distance</th><td>${formatNumber(latest.distance_m,3)} m</td></tr><tr><th>Range margin</th><td>${formatNumber(latest.range_margin_m,3)} m</td></tr><tr><th>Path loss</th><td>${formatNumber(latest.path_loss_db,3)} dB</td></tr><tr><th>Received power</th><td>${formatNumber(latest.rx_power_dbm,3)} dBm</td></tr><tr><th>SNR / SINR</th><td>${formatNumber(latest.snr_db,3)} / ${formatNumber(latest.sinr_db,3)} dB</td></tr><tr><th>Capacity</th><td>${formatNumber(latest.capacity_mbps,3)} Mbps</td></tr><tr><th>Delay</th><td>${formatNumber(latest.total_delay_ms||latest.delay_ms,4)} ms</td></tr><tr><th>Gate</th><td><strong>${escapeHtml(latest.gate_reason||latest.decision||'UNAVAILABLE')}</strong></td></tr></tbody></table></div>`:`<div class="empty-state"><div><div class="empty-icon">∅</div><strong>No runtime metric row</strong><div class="small-text">Start the packet runtime and verify it with Packet Doctor.</div></div></div>`}</section><section class="card"><div class="card-header"><div><h2>Branch availability</h2><p class="card-description">Independent branch state for parallel and forest modes.</p></div></div><div class="table-wrap"><table><thead><tr><th>Branch</th><th>Samples</th><th>Feasible</th><th>Blocked</th><th>Availability</th></tr></thead><tbody>${Object.entries(analytics.branch_metrics||{}).length?Object.entries(analytics.branch_metrics).map(([branch,m])=>`<tr><td>${escapeHtml(branch)}</td><td>${m.samples}</td><td>${m.feasible}</td><td>${m.blocked}</td><td>${formatNumber(m.availability_pct,2)}%</td></tr>`).join(''):`<tr><td colspan="5">No branch samples.</td></tr>`}</tbody></table></div></section></div>
    <section class="card" style="margin-top:16px"><div class="card-header"><div><h2>Recent metric samples</h2><p class="card-description">Newest ${Math.min(100,rows.length)} samples from ${escapeHtml((snapshot.metric_files||[]).join(', ')||'no file')}.</p></div></div><div class="table-wrap"><table><thead><tr><th>Time</th><th>Branch</th><th>Source</th><th>Destination</th><th>Distance (m)</th><th>SNR (dB)</th><th>Capacity (Mbps)</th><th>Gate reason</th></tr></thead><tbody>${rows.slice(-100).reverse().map(row=>`<tr><td>${row.timestamp?new Date(Number(row.timestamp)*1000).toLocaleTimeString():'—'}</td><td>${escapeHtml(row.branch_id||row.branch||'—')}</td><td>${escapeHtml(row.src||'—')}</td><td>${escapeHtml(row.dst||'—')}</td><td>${formatNumber(row.distance_m,2)}</td><td>${formatNumber(row.snr_db,2)}</td><td>${formatNumber(row.capacity_mbps,2)}</td><td><strong>${escapeHtml(row.gate_reason||row.decision||'—')}</strong></td></tr>`).join('')}</tbody></table></div></section>
    <details class="card" style="margin-top:16px"><summary><strong>Telemetry analytics and event inspector</strong></summary><div class="grid two" style="margin-top:14px">${prettyJson(analytics)}${prettyJson(events.slice(-50))}</div></details>`;
    root.querySelector('#telemetry-refresh').addEventListener('click',render);root.querySelector('#telemetry-export').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(snapshot,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`netlab_telemetry_${Date.now()}.json`;a.click();URL.revokeObjectURL(url);toast('Telemetry snapshot exported.','success')});
  };
  await render();
  let pollInterval=null; let viewWatcher=null; let stream=null;
  const stopAll=()=>{stopped=true;if(pollInterval)clearInterval(pollInterval);if(viewWatcher)clearInterval(viewWatcher);if(stream)stream.close()};
  const startPolling=()=>{if(pollInterval||stopped)return;pollInterval=setInterval(()=>{if(state.currentView!=='telemetry'||!root.isConnected){stopAll();return}render()},2000)};
  if('EventSource' in window){
    stream=new EventSource('/api/telemetry/stream');
    stream.addEventListener('telemetry',event=>{try{snapshot=JSON.parse(event.data);state.set('telemetry',snapshot);draw()}catch(error){console.error('Telemetry stream parse error',error)}});
    stream.onerror=()=>{stream.close();stream=null;startPolling()};
    viewWatcher=setInterval(()=>{if(state.currentView!=='telemetry'||!root.isConnected)stopAll()},1000);
  }else startPolling();
}
