import { api } from './api.js';
import { escapeHtml, toast, viewHeader } from './components.js';

export async function renderTrafficServices(root) {
  const response=await api.config(); let config=structuredClone(response.config); const flows=config.traffic.flows;
  const render=()=>{
    root.innerHTML=`${viewHeader('Traffic & Services','Define multiple communication flows, service classes, packet generation, queueing, scheduling, latency budgets, and reliability targets.',`<button class="button secondary" id="flow-add">Add Flow</button><button class="button primary" id="flow-save">Apply Traffic Model</button>`)}
    <section class="card"><div class="card-header"><div><h2>Service flows</h2><p class="card-description">Metrics such as BER, BLER, HARQ, and MCS remain explicitly unavailable unless the selected fidelity implements them.</p></div></div><div class="table-wrap"><table><thead><tr><th>ID</th><th>Source</th><th>Destination</th><th>Service class</th><th>Generation</th><th>Packet bytes</th><th>Rate (pps)</th><th>Delay SLA (ms)</th><th>Reliability</th><th></th></tr></thead><tbody>
      ${flows.map((flow,index)=>`<tr data-flow="${index}"><td><input data-key="id" value="${escapeHtml(flow.id)}"></td><td><input data-key="source" value="${escapeHtml(flow.source)}"></td><td><input data-key="destination" value="${escapeHtml(flow.destination)}"></td><td><select data-key="service_class">${['flight_control','swarm_coordination','network_management','emergency','user_data','sensor_data','video','best_effort'].map(v=>`<option value="${v}" ${flow.service_class===v?'selected':''}>${v}</option>`).join('')}</select></td><td><select data-key="generation_model">${['constant_packet_rate','constant_bit_rate','poisson','on_off','trace_replay','plugin'].map(v=>`<option value="${v}" ${flow.generation_model===v?'selected':''}>${v}</option>`).join('')}</select></td><td><input data-key="packet_size_bytes" type="number" value="${flow.packet_size_bytes}"></td><td><input data-key="packet_rate_pps" type="number" step="any" value="${flow.packet_rate_pps || 0}"></td><td><input data-key="max_delay_ms" type="number" step="any" value="${flow.max_delay_ms || 0}"></td><td><input data-key="reliability_target" type="number" min="0" max="1" step="0.001" value="${flow.reliability_target || 0}"></td><td><button class="button danger small" data-flow-delete="${index}" ${flows.length<=1?'disabled':''}>Delete</button></td></tr>`).join('')}
    </tbody></table></div></section>
    <div class="grid three" style="margin-top:16px"><section class="card"><h2>Queueing</h2><label class="field"><span><strong>Default queue model</strong></span><select id="traffic-queue">${['fifo','priority','per_flow','bounded_fifo','plugin'].map(v=>`<option value="${v}" ${config.traffic.queue_model===v?'selected':''}>${v}</option>`).join('')}</select></label></section><section class="card"><h2>Scheduling</h2><label class="field"><span><strong>Scheduler</strong></span><select id="traffic-scheduler">${['round_robin','weighted_round_robin','strict_priority','tdma','plugin'].map(v=>`<option value="${v}" ${config.traffic.scheduler===v?'selected':''}>${v}</option>`).join('')}</select></label></section><section class="card"><h2>Model availability</h2><div class="stack"><span class="status-chip ready">PACKET / QUEUE MODELLED</span><span class="status-chip warning">BER / BLER NOT MODELLED</span><span class="status-chip warning">HARQ / MCS NOT MODELLED</span></div></section></div>`;
    function collect(){root.querySelectorAll('[data-flow]').forEach(row=>{const flow=flows[Number(row.dataset.flow)];for(const key of ['id','source','destination','service_class','generation_model'])flow[key]=row.querySelector(`[data-key="${key}"]`).value;for(const key of ['packet_size_bytes','packet_rate_pps','max_delay_ms','reliability_target'])flow[key]=Number(row.querySelector(`[data-key="${key}"]`).value)});config.traffic.queue_model=root.querySelector('#traffic-queue').value;config.traffic.scheduler=root.querySelector('#traffic-scheduler').value}
    root.querySelector('#flow-add').addEventListener('click',()=>{flows.push({id:`flow_${flows.length+1}`,source:'station',destination:`drone_${config.swarm.relay_count}`,branch_id:'branch_0',service_class:'user_data',generation_model:'constant_packet_rate',packet_size_bytes:512,packet_rate_pps:1,priority:1,max_delay_ms:150,min_throughput_mbps:1,reliability_target:.99,queue_capacity_packets:128,start_time_s:0,stop_time_s:config.experiment.duration_s});render()});
    root.querySelectorAll('[data-flow-delete]').forEach(button=>button.addEventListener('click',()=>{flows.splice(Number(button.dataset.flowDelete),1);render()}));
    root.querySelector('#flow-save').addEventListener('click',async event=>{event.currentTarget.disabled=true;try{collect();const result=await api.saveConfig(config,true);config=structuredClone(result.config);toast(result.committed?'Traffic model committed across runtime participants.':`Traffic draft saved; runtime state is ${result.synchronization?.state || 'PENDING_RUNTIME_APPLY'}.`,result.committed?'success':'warning',8000);render()}catch(error){toast(error.message,'error')}finally{event.currentTarget.disabled=false}})
  };render();
}
